#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dfu-util
Version  : 0.11
Release  : 6
URL      : https://sourceforge.net/projects/dfu-util/files/dfu-util-0.11.tar.gz
Source0  : https://sourceforge.net/projects/dfu-util/files/dfu-util-0.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: dfu-util-bin = %{version}-%{release}
Requires: dfu-util-license = %{version}-%{release}
Requires: dfu-util-man = %{version}-%{release}
BuildRequires : pkgconfig(libusb-1.0)

%description
Dfu-util - Device Firmware Upgrade Utilities
Dfu-util is a host side implementation of the DFU 1.0 and DFU 1.1 [1]
specification of the USB forum.

%package bin
Summary: bin components for the dfu-util package.
Group: Binaries
Requires: dfu-util-license = %{version}-%{release}

%description bin
bin components for the dfu-util package.


%package license
Summary: license components for the dfu-util package.
Group: Default

%description license
license components for the dfu-util package.


%package man
Summary: man components for the dfu-util package.
Group: Default

%description man
man components for the dfu-util package.


%prep
%setup -q -n dfu-util-0.11
cd %{_builddir}/dfu-util-0.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631722803
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1631722803
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dfu-util
cp %{_builddir}/dfu-util-0.11/COPYING %{buildroot}/usr/share/package-licenses/dfu-util/dfac199a7539a404407098a2541b9482279f690d
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dfu-prefix
/usr/bin/dfu-suffix
/usr/bin/dfu-util

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dfu-util/dfac199a7539a404407098a2541b9482279f690d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dfu-prefix.1
/usr/share/man/man1/dfu-suffix.1
/usr/share/man/man1/dfu-util.1
