#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dfu-util
Version  : 0.9
Release  : 1
URL      : http://dfu-util.sourceforge.net/releases/dfu-util-0.9.tar.gz
Source0  : http://dfu-util.sourceforge.net/releases/dfu-util-0.9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: dfu-util-bin
Requires: dfu-util-doc
BuildRequires : pkgconfig(libusb-1.0)

%description
Dfu-util - Device Firmware Upgrade Utilities
Dfu-util is the host side implementation of the DFU 1.0 [1] and DFU 1.1 [2]
specification of the USB forum.

%package bin
Summary: bin components for the dfu-util package.
Group: Binaries

%description bin
bin components for the dfu-util package.


%package doc
Summary: doc components for the dfu-util package.
Group: Documentation

%description doc
doc components for the dfu-util package.


%prep
%setup -q -n dfu-util-0.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523570641
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1523570641
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dfu-prefix
/usr/bin/dfu-suffix
/usr/bin/dfu-util

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
